hints_override:
  'и': [['CONJ']]
  'виледор': [['masc']]

static_proverbs:
  'поползень':
  - 'один в попе не поползень'
  - 'сделал поползень - гуляй поползень'
  - 'старый поползень ковра не испортит'
  - 'в тихом поползне блохи водятся'
  - 'в здоровом поползне - здоровый веник'
  - 'будешь долго мучиться – поползень получится'

  'веник':
  - 'лучше веник в руках, чем швабра в небе'
  - 'старый веник ковра не испортит'
  - 'в здоровом венике - здоровый поползень'

  'Ташон':
  - 'Ташон, держи корнишон'
  - 'меня сташонило'
  - 'целая банка Ташонки'
  - 'работа - не Ташон, на зомбей не побежит'
  - 'был бы зомби, а Ташон найдётся'
  - 'Ташон в гору не пойдёт, Ташон же бот'
  - 'уф, меня Ташонит'
  - 'лучше Ташон в руках, чем пк-гейминг в небе'
  - 'Ташонск прекрасен в это время года'
  - 'Ташона стримеры кормят'
  - 'был бы 3D, а Ташон найдётся'

  'Салим':
  - 'работа - не Салим, на вампира не побежит'
  - 'был бы вампир, а Салим найдётся'

  'зомби': []

proverbs:
- '{ablt_plur} после драки не машут'
- '{ablt} игру не испортишь'
- '{ablt} кашу не испортишь'
- '{ablt} стены не прошибёшь'
- '{gent_plur} бояться – в лес не ходить'
- '{accs_plur} по осени считают'
- '{accs} {ablt_plur} вышибают'
- '{accs} в ступе толочь – {nomn} и будет'
- '{accs} рубят - щепки летят'
- '{datv_plur} закон не писан'
- '{datv} все возрасты покорны'
- '{datv} море по колено, а лужа – по уши'
- '{datv} не прикажешь'
- '{gent} три года ждут'
- '{nomn} - не воробей, вылетит - не поймаешь'
- '{nomn} {datv} рознь'
- '{nomn} {gent} видит издалека'
- '{nomn} борозды не испортит'
- '{nomn} всему голова'
- '{nomn} живи, {nomn} учись'
- '{nomn} и я - весёлая семья'
- '{nomn} камень точит'
- '{nomn} не сразу строился'
- '{nomn} никогда не приходит один'
- '{nomn} от {gent} недалеко падает'
- '{nomn} приходит во время еды'
- '{nomn} с возу - кобыле легче'
- '{nomn} с возу - игре легче'
- '{nomn} свинье не товарищ'
- 'без {gent} игра вылетает'
- 'без {gent} не вытащить и рыбку из пруда'
- 'без {gent} уже и жизнь не та'
- 'без труда не выловишь и {gent} из пруда'
- 'болтун – находка для {gent}'
- '{nomn} - находка для шпиона'
- 'большому {datv} – большое плавание'
- 'большому кораблю – большой {nomn}'
- 'был бы {nomn} - остальное приложится'
- 'был бы {nomn}... был бы {nomn}.'
- 'в гостях хорошо, а с {ablt} лучше'
- 'в семье не без {gent}'
- 'в тихом омуте {nomn_plur} водятся'
- 'в чужой монастырь со своим {ablt} не ходят'
- 'в чужом {loct} соринку видим, а в своём бревна не замечаем'
- 'в чужом глазу соринку видим, а в своём {accs} не замечаем'
- 'видна птица по полёту, а {nomn} – по делам'
- 'волка {nomn} кормит'
- 'всему свой {nomn}'
- 'где родился, там и {nomn}'
- 'глаза боятся, а в руках - {nomn}'
- 'гора с горой не сходится, а {nomn} с {ablt} сойдётся'
- 'дарёному {datv} в зубы не смотрят'
- 'два {gent} - пара'
- 'два {gent} в одной берлоге не живут'
- 'два сапога - {nomn}'
- 'дворника {nomn} кормит'
- 'дело {gent} боится'
- 'делу время, {datv} час'
- 'делу время, потехе {nomn}'
- 'долг {ablt} красен'
- 'других не суди, на {accs} погляди'
- 'дружба дружбой, а {nomn} {ablt}'
- 'если в кране нет воды - значит, {accs} туды!'
- 'ехал {nomn} через {accs}, видит {nomn} в {loct} - {accs}, сунул {nomn} {accs} в {accs}, {nomn} {nomn} {nomn} {nomn}'
- 'жил как {nomn} и умер как {nomn}'
- 'за двумя {ablt_plur} погонишься, ни одного не поймаешь'
- 'за деревьями {accs} не видать'
- 'за себя и за {accs}'
- 'каждый может стать {ablt}'
- 'каждый судит по {datv}'
- 'как {accs} назовёшь, так он и поплывёт'
- 'когда {nomn} на горе свистнет'
- 'коопу время, {datv} час'
- 'копейка {accs} бережёт'
- 'красна изба не углами, а {ablt_plur}'
- 'красота требует {gent_plur}'
- 'кто первым встал, того и {nomn}'
- 'лучше горький {nomn}, чем сладкая ложь'
- 'любишь играть, люби и {accs} в катку брать'
- 'любишь кататься, люби и {accs} возить'
- 'мал {nomn}, да {nomn}'
- 'мал {nomn}, да вонюч'
- 'мал {nomn}, да могуч'
- 'меньше знаешь - крепче {nomn}'
- 'мир не без добрых {gent_plur}'
- 'на {accs} надейся, а сам не плошай'
- 'на {loct_plur} воду возят'
- 'на безрыбье и {nomn} - рыба'
- 'на вкус и цвет {gent_plur} нет'
- 'на ловца и {nomn} бежит'
- 'на нет и {gent} нет'
- 'на обиженных {gent_plur} возят'
- 'назвался {ablt} - полезай в игру'
- 'нашёл {nomn} на камень'
- 'не было {gent}, да {nomn} помог'
- 'не всё то {nomn}, что блестит'
- 'не имей 100 друзей, а имей 1 {accs}'
- 'не каждая птица долетит до середины {gent}'
- 'не место красит {accs}, а {nomn} место'
- 'не плюй в колодец, вдруг там {nomn}'
- 'не пойман - не {nomn}'
- 'не рой яму {datv} – сам в неё попадёшь'
- 'не разбив яиц, {accs} не приготовишь'
- 'не разбив {accs}, омлет не приготовишь'
- 'не так страшен {nomn}, как его малюют'
- 'нет худа без {gent}'
- 'ни рыба, ни {nomn}'
- 'ничто не истинно, всё {nomn}'
- 'новый {nomn} лучше старых двух, а когда сломается - под лавкою валяется'
- 'один {nomn} хорошо, а два - лучше'
- 'один {nomn} хорошо, а еще один - перебор'
- 'один за {nomn} - всегда {nomn}'
- 'один в поле не {nomn}'
- 'один пашет - семеро {ablt_plur} машут'
- 'один старый {nomn} лучше новых двух'
- 'от {gent} никто не застрахован'
- 'от любви до {gent} - один шаг'
- 'первый {nomn} комом'
- 'по одёжке встречают, по {datv} провожают'
- 'покажи, где {nomn_plur} зимуют'
- 'поспешишь – {accs} насмешишь'
- 'пуганая ворона и {gent} боится'
- 'раз в год и {nomn} стреляет'
- 'рыба ищет, где глубже, а {nomn} – где лучше'
- 'с миру по нитке - {datv} рубаха'
- 'семь раз отмерь, один раз {nomn}'
- 'сколько {accs} не корми - всё равно {nomn}'
- 'сколько {accs} не корми, а его всё в лес тянет'
- 'сколько стримера не корми, а он всё на {accs} смотрит'
- 'слово - не {nomn}, вылетит - не поймаешь'
- 'слово – серебро, молчание – {nomn}'
- 'сначала думай, а потом {nomn}'
- 'тише едешь - дальше {nomn}'
- 'у страха {nomn_plur} велики'
- 'утопающий и за {accs} хватается'
- 'ученье - свет, а неученье - {nomn}'
- 'человек человеку друг, а {nomn} {datv} - {nomn}'
- 'чем дальше в лес, тем больше {gent_plur}'
- 'я календарь переверну, а там {nomn}'
