options:
  bots:
  - nightbot
  - streamelements
  range:
    min: 0
    max: 150
groups:
- name: ICQ
  weight: 100
  templates:
    simple: 'у вас {value} ICQ {emote}'
    delta: 'у вас {value} ICQ ({delta}) {emote}'
  emotes:
  - SabaPing
  - SlowPoke
  - MonkaChiken
  - BSUL
  - ANYA
  - bufaRage
  - bufaDumb
  - SMOrc
  - dead5What
  - bufaUL
  - BSUHee
  - Pepega
  - BSUTrolled
  - bufaHee
  - UHMMM
  - YEPP
  - MmmHmm
  - peepoThink
  - Coffeege
  - PepoG
  - ZZoomer
  - BUFANerd
  - OMEGABSU
  - HACKERMANS
  - bufaSm
  - 5Head
  - Sherlock
  - Kojimaptyp
  special:
    '0': bufaPressF drhx.ru/iq0
    '69': BSUHey
    '150': gachiOnFIRE
- name: AYAYA
  weight: 10
  templates:
    simple: 'ваш уровень AYAYAшности: {value} {emote}'
    delta: 'ваш уровень AYAYAшности: {value} ({delta}) {emote}'
  emotes:
  - popCat
  - loliTriggered
  - PunOko
  - TPcrunchyroll
  - PinkMercy
  - TPFufun
  - VoHiYo
  - TaBeRu
  - KonCha
  - HungryPaimon
  - Paimon
  - bufaSugoi
  - TehePelo
  - AYAYA
  special:
    '69': RiasSenpai
    '150': AYAYA AYAYA AYAYA
- name: ANYA
  weight: 10
  templates:
    simple: 'вы состоите на {value}% из борща {emote}'
    delta: 'вы состоите на {value}% из борща ({delta}) {emote}'
  emotes:
  - bufaRRage
  - Nervous
  - BSEpt
  - bufaUL
  - BSNONO
  - WTFFF
  - Tastge
  - BSUSHO
  - ANYA
  special:
    '0': NoWay
    '69': DealWithIt
    '150': BSURage
- name: popCat
  weight: 10
  templates:
    simple: 'у вас {value} пополз{value#ень,ня,ней} {emote}'
    delta: 'у вас {value} пополз{value#ень,ня,ней} ({delta}) {emote}'
  emotes:
  - pauseCat
  - popCat
  - popCat popCat
  special:
    '69': bufaLewd
    '150': popCat popCat popCat
- name: bipki
  weight: 10
  templates:
    simple: 'у вас {value} бип{value#ка,ки,ок} {emote}'
    delta: 'у вас {value} бип{value#ка,ки,ок} ({delta}) {emote}'
  emotes:
  - SlowPoke
  - ppBounce
  - peepoThink
  - ppCircle
  - pauseCat
  - ppHop
  - UHMMM
  - ANYA
  special:
    '150': ppHop ppCircle ppBounce
